const { Router } = require("express");

const register = require("../controllers/Employee/registerEmployee");
const login = require("../controllers/Employee/login");
const logout = require("../controllers/Employee/logout");
const consulApi = require("../controllers/consultApi/apiRuc");
const verifyToken = require("../controllers/auth/verifyToken");
const postPermissions = require("../controllers/Permissions/postPermissions");
const getPermissions = require("../controllers/Permissions/getPermissions");
const createModule = require("../controllers/Modules/createModule");
const createSubmodule = require("../controllers/SubModules/createSubModule");
const getSubModules = require("../controllers/SubModules/getsubModule");
const getModules = require("../controllers/Modules/getModules");
const getEmployee = require("../controllers/Employee/getEmployee");
const updateEmployeePartial = require("../controllers/Employee/updateEmployee");
const createClient = require("../controllers/Client/createClient");
const getClients = require("../controllers/Client/getClients");
const updateClient = require("../controllers/Client/updateClient");
const deleteClient = require("../controllers/Client/deleteClient");
const createCotizacion = require("../controllers/Cotización/createCotizacion");
const getCotizaciones = require("../controllers/Cotización/getCotizacion");
const deleteCotizacion = require("../controllers/Cotización/deleteCotizacion");
const updateCotizacionPartial = require("../controllers/Cotización/updateCotizacion");
const allContracts = require("../controllers/Contracts/allContracts");
const postContracts = require("../controllers/Contracts/postContracts");
const putContracts = require("../controllers/Contracts/putContracts");
const getBusiness = require("../controllers/AllModulos/RecursosHumanos/Business/getBusiness");
const deleteBusiness = require("../controllers/AllModulos/RecursosHumanos/Business/deleteBusiness");
const updateBusinessPartial = require("../controllers/AllModulos/RecursosHumanos/Business/updateBusiness");
const createBusiness = require("../controllers/AllModulos/RecursosHumanos/Business/postBusiness");
const postPlantillasDeContrato = require("../controllers/AllModulos/RecursosHumanos/PlantillasDeContrato/postPlantillasDeContrato");
const getAllPlantillasDeContrato = require("../controllers/AllModulos/RecursosHumanos/PlantillasDeContrato/getAllPlantillasDeContrato");
const deletePlantillaContrato = require("../controllers/AllModulos/RecursosHumanos/PlantillasDeContrato/deletePlantillaContrato");
const putPlantillaDeContrato = require("../controllers/AllModulos/RecursosHumanos/PlantillasDeContrato/putPlantillaDeContrato");
const getAllAsistenciaColaborador = require("../controllers/AllModulos/RecursosHumanos/Asistencia/colaborador/getAsistenciaColaborador");
const postAsistenciaColaborador = require("../controllers/AllModulos/RecursosHumanos/Asistencia/colaborador/postAsistenciaColaborador");
const deleteAsistenciaColaborador = require("../controllers/AllModulos/RecursosHumanos/Asistencia/colaborador/deleteAsistenciaColaborador");
const getBoletaDePagos = require("../controllers/AllModulos/RecursosHumanos/BoletaDePagos/getBoletaDePagos");
const postBoletaDePagos = require("../controllers/AllModulos/RecursosHumanos/BoletaDePagos/postBoletaDePagos");
const postDatosContables = require("../controllers/AllModulos/RecursosHumanos/BoletaDePagos/postDatosContables");
const getDatosContables = require("../controllers/AllModulos/RecursosHumanos/BoletaDePagos/getDatosContables");
const patchBoleDePago = require("../controllers/AllModulos/RecursosHumanos/BoletaDePagos/patchBoletaDePago");
const enviarBoleta = require("../controllers/AllModulos/RecursosHumanos/BoletaDePagos/enviarBoleta");
const recepcionBoleta = require("../controllers/AllModulos/RecursosHumanos/BoletaDePagos/recibirBoleta");
const updateAsistenciaColaborador = require("../controllers/AllModulos/RecursosHumanos/Asistencia/colaborador/updateAsistenciaColaborador");
const deleteBoletaDePago = require("../controllers/AllModulos/RecursosHumanos/BoletaDePagos/deleteBoletaDePago");
const subirBoletas = require("../controllers/AllModulos/RecursosHumanos/BoletaDePagos/subirBoletas");
const EliminarDocumento = require("../controllers/AllModulos/RecursosHumanos/BoletaDePagos/eliminarDocumento");
const getEmployeeById = require("../controllers/Employee/getEmployeById");
const getContractById = require("../controllers/Contracts/getContractById");
const getCertificados = require("../controllers/AllModulos/Certificaciones/Certificados/getCertificados");
const postCertificado = require("../controllers/AllModulos/Certificaciones/Certificados/postCertificados");
const deleteContract = require("../controllers/Contracts/deleteContracts");
const postWidget = require("../controllers/Herramientas/Widgets/postWidgets");
const deleteWidget = require("../controllers/Herramientas/Widgets/deleteWidget");
const getAllWidgets = require("../controllers/Herramientas/Widgets/getAllWidgets");
const patchWidget = require("../controllers/Herramientas/Widgets/patchWidget");
const addWidgetEmployee = require("../controllers/Herramientas/Widgets/widgetEmployee");
const getWidgetEmployee = require("../controllers/Herramientas/Widgets/getWidgetEmployee");
const updateWidgetPreference = require("../controllers/Herramientas/Widgets/updateWidgetPreference");
const deleteSubmodule = require("../controllers/SubModules/deleteSubmodule");
const deleteModule = require("../controllers/Modules/deleteModule");
const getAllNotificaciones = require("../controllers/Herramientas/Notification/getNotification");
const returnPdf = require("../controllers/AllModulos/RecursosHumanos/Asistencia/colaborador/returnPdf");
const getAllContratos = require("../controllers/AllModulos/Almacen/Contrato/getContrato");
const postContratoAlmacen = require("../controllers/AllModulos/Almacen/Contrato/postContrato");
const getAllSedesAlmacen = require("../controllers/AllModulos/Almacen/Ubicacion/getAllSedes");
const postSedesAlmacen = require("../controllers/AllModulos/Almacen/Ubicacion/postSedesAlmacen");
const createMovimiento = require("../controllers/AllModulos/Almacen/Movimientos/postMovimientos");
const getAllMovimientosBySede = require("../controllers/AllModulos/Almacen/Movimientos/getMovimientosBySede");
const postAlmacen = require("../controllers/AllModulos/Almacen/Almacen/postAlmacen");
const getAllNavesAlmacen = require("../controllers/AllModulos/Almacen/Almacen/getAllNavesAlmacen");
const getAllZonas = require("../controllers/AllModulos/Almacen/Ubicacion/getAllZonas");
const postZonaAlmacen = require("../controllers/AllModulos/Almacen/Ubicacion/postZona");
const deleteZonaAlmacen = require("../controllers/AllModulos/Almacen/Ubicacion/deleteZona");
const postUbicacion = require("../controllers/AllModulos/Almacen/Ubicacion/postUbicacion");
const deleteNaveAlmacen = require("../controllers/AllModulos/Almacen/Almacen/deleteAlmacen");
const deleteSedeAlmacen = require("../controllers/AllModulos/Almacen/Ubicacion/deleteSede");
const getUbicacionByParams = require("../controllers/AllModulos/Almacen/Ubicacion/getUbicacionBySection");
const patchUbicacion = require("../controllers/AllModulos/Almacen/Ubicacion/patchUbicacion");
const postStockAlmacen = require("../controllers/AllModulos/Almacen/Stock/postStock");
const deleteMovimientoAlmacen = require("../controllers/AllModulos/Almacen/Movimientos/deleteMovimiento");
const getStockByParams = require("../controllers/AllModulos/Almacen/Stock/getStockParams");
const getAsistenciaByParams = require("../controllers/AllModulos/RecursosHumanos/Asistencia/colaborador/getAsistenciaByParams");
const getStockProductoUbicacion = require("../controllers/AllModulos/Almacen/Stock/getStockProductoUbicacion");
const patchStockAlmacen = require("../controllers/AllModulos/Almacen/Stock/patchStock");
const patchMovimiento = require("../controllers/AllModulos/Almacen/Movimientos/patchMovimiento");
const getBoletaDePagoByParams = require("../controllers/AllModulos/RecursosHumanos/BoletaDePagos/getBoletaDePagoByParams");
const getEmployeeByParams = require("../controllers/Employee/getEmployeeByParam");
const getZonasByParams = require("../controllers/AllModulos/Almacen/Ubicacion/getZonaByParams");
const getNavesBySede = require("../controllers/AllModulos/Almacen/Almacen/getNavesBySede");
const getMovimientoByCodigo = require("../controllers/AllModulos/Almacen/Movimientos/getMovimientoByCodigo");
const getStockAlmacen = require("../controllers/AllModulos/Almacen/Stock/getStock");
const getNavesPagination = require("../controllers/AllModulos/Almacen/Almacen/getNavesPagination");
const getZonaPagination = require("../controllers/AllModulos/Almacen/Ubicacion/getZonaPagination");
const getSedePagination = require("../controllers/AllModulos/Almacen/Ubicacion/getSedePagination");
const deleteContratoAlmacen = require("../controllers/AllModulos/Almacen/Contrato/deleteContrato");
const getContratoAlmacenPagination = require("../controllers/AllModulos/Almacen/Contrato/getContratoPagiancion");
const deleteStockAlmacen = require("../controllers/AllModulos/Almacen/Stock/deleteStockAlmacen");
const sistemasRouter = require("./Modulos/sistemas");
const recursosHumanosRouter = require("./Modulos/RecursosHumanos");
const herramientasRouter = require("./Modulos/Herramientas");
const certificacionesRouter = require("./Modulos/Certificacion");
const postAsistenciaApp = require("../controllers/AllModulos/RecursosHumanos/Asistencia/colaborador/postAsistenciaApp");
const almacenLurinRouter = require("./Modulos/Almcen");
const updateAsistenciaGestower = require("../controllers/AllModulos/RecursosHumanos/Asistencia/colaborador/patchAsistenciaApp");
const manifesTower = require("./Modulos/ManifesTower");

const router = Router();

router.post("/registerEmployee", register);
router.post("/login", login);
router.post("/logout", logout);
router.post("/postPermissions", postPermissions);
router.post("/postModule", createModule);
router.post("/postSubmodule", createSubmodule);
router.post("/createBusiness", createBusiness);
router.post("/createClient", createClient);
router.post("/createCotizacion", createCotizacion);
router.post("/createContract", postContracts);
router.post("/postPlantillasDeContrato", postPlantillasDeContrato);
router.post("/postAsistenciaColaborador", postAsistenciaApp);
router.post("/postAsistenciaErp", postAsistenciaColaborador);
router.post("/postBoletaDePagos", postBoletaDePagos);
router.post("/postDatosContables", postDatosContables);
router.post("/enviarBoletasDePago", enviarBoleta);
router.post("/boletajson", subirBoletas);
router.post("/postCertificado", postCertificado);
router.post("/postWidget", postWidget);
router.post("/addWidgetPreference", addWidgetEmployee);
router.post("/returnPdf", returnPdf);
router.post("/postContratoAlmacen", postContratoAlmacen);
router.post("/postSedesAlmacen", postSedesAlmacen);
router.post("/postMovimientoAlmacen", createMovimiento);
router.post("/postNavesAlmacen", postAlmacen);
router.post("/postZonaAlmacen", postZonaAlmacen);
router.post("/postUbicacionProducto", postUbicacion);
router.post("/postStockAlmacen", postStockAlmacen);

router.patch("/patchMovimientoAlmacen", patchMovimiento);
router.patch("/patchStockAlmacen", patchStockAlmacen);
router.patch("/patchUbicacionProducto", patchUbicacion);
router.patch("/patchNavesAlmacen", deleteNaveAlmacen);
router.patch("/patchBusiness", updateBusinessPartial);
router.patch("/patchCotizacion", updateCotizacionPartial);
router.patch("/patchEmployee", updateEmployeePartial);
router.patch("/patchClient", updateClient);
router.patch("/patchContract", putContracts);
router.patch("/patchPlantillaDeContrato", putPlantillaDeContrato);
router.patch("/patchAsistenciaColaborador", updateAsistenciaColaborador);
router.patch("/patchAsistenciaERP", updateAsistenciaGestower);
router.patch("/patchBoletaDePago", patchBoleDePago);
router.patch("/patchWidget", patchWidget);
router.patch("/updateWidgetPreference", updateWidgetPreference);

router.delete("/deleteSedesAlmacen", deleteSedeAlmacen);
router.delete("/deleteBoletaDePago", deleteBoletaDePago);
router.delete("/deleteClient", deleteClient);
router.delete("/deleteCotizacion", deleteCotizacion);
router.delete("/deleteBusiness", deleteBusiness);
router.delete("/deletePlantillaContrato", deletePlantillaContrato);
router.delete("/deleteAsistenciaColaborador", deleteAsistenciaColaborador);
router.delete("/deleteDocument", EliminarDocumento);
router.delete("/deleteContract", deleteContract);
router.delete("/deleteWidget", deleteWidget);
router.delete("/deleteSubmodule", deleteSubmodule);
router.delete("/deleteModule", deleteModule);
router.delete("/deleteZonaAlmacen", deleteZonaAlmacen);
router.delete("/deleteNavesAlmacen", deleteNaveAlmacen);
router.delete("/deleteMovimientoAlmacen", deleteMovimientoAlmacen);
router.delete("/deleteContratoAlmacen", deleteContratoAlmacen);
router.delete("/deleteStockAlmacen", deleteStockAlmacen);

router.get("/getContratosAlmacenPagination", getContratoAlmacenPagination);
router.get("/getNavesAlmacenPagination", getNavesPagination);
router.get("/getSedesAlmacenPagination", getSedePagination);
router.get("/getZonasPagination", getZonaPagination);
router.get("/getMovimientoByCodigo", getMovimientoByCodigo);
router.get("/getNavesBySede", getNavesBySede);
router.get("/getZonasByParams", getZonasByParams);
router.get("/getEmployeeByParams", getEmployeeByParams);
router.get("/getBoletaDePagoByParams", getBoletaDePagoByParams);
router.get("/getStockProductoUbicacion", getStockProductoUbicacion);
router.get("/getAsistenciaByParams", getAsistenciaByParams);
router.get("/getStockByParams", getStockByParams);
router.get("/getStockAlmacen", getStockAlmacen);
router.get("/getUbicacionByParams", getUbicacionByParams);
router.get("/getAllZonas", getAllZonas);
router.get("/getNavesAlmacen", getAllNavesAlmacen);
router.get("/getAllMovimientosBySede", getAllMovimientosBySede);
router.get("/getAllSedesAlmacen", getAllSedesAlmacen);
router.get("/getAllContratoAlmacen", getAllContratos);
router.get("/getAllNotificaciones", getAllNotificaciones);
router.get("/getWidgetsPreference/:colaborador", getWidgetEmployee);
router.get("/getAllWidgets", getAllWidgets);
router.get("/getCertificados", getCertificados);
router.get("/recepcionBoleta", recepcionBoleta);
router.get("/getDatosContables", getDatosContables);
router.get("/getBoletaDePagos", getBoletaDePagos);
router.get("/getAllAsistenciaColaborador", getAllAsistenciaColaborador);
router.get("/getPlantillasDeContrato", getAllPlantillasDeContrato);
router.get("/allContracts", allContracts);
router.get("/contract/:id", getContractById);
router.get("/getCotizaciones", getCotizaciones);
router.get("/getClients", getClients);
router.get("/getBusiness", getBusiness);
router.get("/getModules", getModules);
router.get("/getSubModules", getSubModules);
router.get("/getPermissions", getPermissions);
router.get("/auth/verify", verifyToken);
router.get("/employee", getEmployee);
router.get("/employee/:id", getEmployeeById);
router.get("/ruc", consulApi);

router.use("/sistemas", sistemasRouter);
router.use("/almacenLurin", almacenLurinRouter);
router.use("/rrhh", recursosHumanosRouter);
router.use("/herramientas", herramientasRouter);
router.use("/certificaciones", certificacionesRouter);
router.use("/manifesTower", manifesTower);

module.exports = router;
